[package]
name = "d24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
f128 = "0.2.9"
regex = "1.10.2"
